import { db } from '@/db';
import { species } from '@/db/schema';

async function main() {
    const sampleSpecies = [
        {
            category: 'crop',
            commonName: 'Rice',
            scientificName: 'Oryza sativa',
            family: 'Poaceae',
            tags: JSON.stringify(['kharif', 'cereal', 'staple']),
            growthHabit: 'herb',
            lifecycle: 'annual',
            climate: 'Warm and humid, 25-35°C, 1500-2000mm rainfall',
            region: 'West Bengal, Punjab, Uttar Pradesh, Andhra Pradesh',
            soil: 'Clay loam, pH 5.5-7.0',
            water: 'Submerged, 1500-2500mm',
            sunlight: 'Full sun, 6-8 hours',
            spacing: '20x15 cm',
            sowingPlanting: 'June-July, transplanting',
            fertilization: 'NPK 120:60:40 kg/ha',
            pests: 'Stem borer, Brown planthopper, Gall midge',
            diseases: 'Blast, Bacterial blight, Sheath blight',
            management: 'IPM, resistant varieties, proper water management',
            harvest: '125-135 days, grains harden and turn golden',
            yield: '5-8 t/ha',
            seasonality: 'Kharif',
            uses: 'Food, fodder, industrial products',
            imageUrl: 'https://example.com/rice.jpg',
            language: 'en',
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            category: 'crop',
            commonName: 'Wheat',
            scientificName: 'Triticum aestivum',
            family: 'Poaceae',
            tags: JSON.stringify(['rabi', 'cereal', 'staple']),
            growthHabit: 'herb',
            lifecycle: 'annual',
            climate: 'Cool and dry, 15-25°C, 300-650mm rainfall',
            region: 'Punjab, Haryana, Uttar Pradesh, Madhya Pradesh',
            soil: 'Loamy, pH 6.0-7.5',
            water: 'Irrigated, 3-5 irrigations',
            sunlight: 'Full sun, 8-10 hours',
            spacing: '15x20 cm',
            sowingPlanting: 'November, broadcasting or drilling',
            fertilization: 'NPK 150:60:40 kg/ha',
            pests: 'Termites, Armyworm, Aphids',
            diseases: 'Rust, Loose smut, Karnal bunt',
            management: 'Seed treatment, timely irrigation, resistant varieties',
            harvest: '110-130 days, golden yellow spikes',
            yield: '4-6 t/ha',
            seasonality: 'Rabi',
            uses: 'Food, fodder',
            imageUrl: 'https://example.com/wheat.jpg',
            language: 'en',
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            category: 'crop',
            commonName: 'Maize',
            scientificName: 'Zea mays',
            family: 'Poaceae',
            tags: JSON.stringify(['kharif', 'cereal', 'cash crop']),
            growthHabit: 'herb',
            lifecycle: 'annual',
            climate: 'Warm temperate to tropical, 20-32°C',
            region: 'Karnataka, Andhra Pradesh, Tamil Nadu, Maharashtra',
            soil: 'Sandy loam to clay loam, pH 6.0-7.0',
            water: '600-1000mm',
            sunlight: 'Full sun, 8-10 hours',
            spacing: '60x25 cm',
            sowingPlanting: 'June-July, kharif; January-February, rabi',
            fertilization: 'NPK 150:75:50 kg/ha',
            pests: 'Shoot fly, Stem borer, Pink borer',
            diseases: 'Downy mildew, Maydis leaf blight',
            management: 'Seed treatment, row spacing, trap crops',
            harvest: '90-110 days, brown husks, dark kernels',
            yield: '6-10 t/ha',
            seasonality: 'Kharif, Rabi',
            uses: 'Food, fodder, industrial products',
            imageUrl: 'https://example.com/maize.jpg',
            language: 'en',
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            category: 'crop',
            commonName: 'Cotton',
            scientificName: 'Gossypium hirsutum',
            family: 'Malvaceae',
            tags: JSON.stringify(['kharif', 'commercial', 'fiber']),
            growthHabit: 'shrub',
            lifecycle: 'annual',
            climate: 'Semi-arid, 25-32°C, moderate humidity',
            region: 'Gujarat, Maharashtra, Punjab, Haryana',
            soil: 'Deep loamy, pH 6.0-8.0',
            water: '700-1200mm, 4-6 irrigations',
            sunlight: 'Full sun, 8-10 hours',
            spacing: '67x60 cm',
            sowingPlanting: 'April-May, pre-monsoon',
            fertilization: 'NPK 120:60:60 kg/ha',
            pests: 'American bollworm, Spotted bollworm, Whitefly',
            diseases: 'Leaf spot, Root rot, Wilt',
            management: 'IPM, Bt varieties, timely sowing',
            harvest: '170-220 days, bolls open and fluff out',
            yield: '2-3 t/ha lint',
            seasonality: 'Kharif',
            uses: 'Textile, oil, animal feed',
            imageUrl: 'https://example.com/cotton.jpg',
            language: 'en',
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            category: 'crop',
            commonName: 'Sugarcane',
            scientificName: 'Saccharum officinarum',
            family: 'Poaceae',
            tags: JSON.stringify(['perennial', 'commercial', 'sugar']),
            growthHabit: 'herb',
            lifecycle: 'perennial',
            climate: 'Hot and humid, 26-32°C, 1200-2500mm rainfall',
            region: 'Uttar Pradesh, Maharashtra, Karnataka, Tamil Nadu',
            soil: 'Deep loamy, pH 6.0-8.0',
            water: '2000-3000mm, 8-10 irrigations',
            sunlight: 'Full sun, 6-8 hours',
            spacing: '75x45 cm',
            sowingPlanting: 'February-April, October-December',
            fertilization: 'NPK 250:100:100 kg/ha',
            pests: 'Stem borer, Gurdaspur borer, Whitefly',
            diseases: 'Red rot, Smut, Mosaic',
            management: 'Seed selection, crop rotation, resistant varieties',
            harvest: '12-16 months, sucrose content >12%',
            yield: '60-100 t/ha',
            seasonality: 'Kharif, spring',
            uses: 'Sugar, jaggery, biofuel',
            imageUrl: 'https://example.com/sugarcane.jpg',
            language: 'en',
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            category: 'crop',
            commonName: 'Turmeric',
            scientificName: 'Curcuma longa',
            family: 'Zingiberaceae',
            tags: JSON.stringify(['spice', 'medicinal', 'kharif']),
            growthHabit: 'herb',
            lifecycle: 'annual',
            climate: 'Tropical, 25-35°C, 1500-2250mm rainfall',
            region: 'Tamil Nadu, Maharashtra, Telangana, Karnataka',
            soil: 'Light loamy, pH 5.0-7.0',
            water: '1500-2250mm, avoid waterlogging',
            sunlight: 'Partial shade, 4-6 hours',
            spacing: '30x25 cm',
            sowingPlanting: 'May-July with monsoon',
            fertilization: 'NPK 30:60:80 kg/ha',
            pests: 'Shoot borer, Rhizome scale',
            diseases: 'Rhizome rot, Leaf blotch',
            management: 'Seed treatment, proper drainage, organic manure',
            harvest: '200-240 days, leaves turn yellow and dry',
            yield: '15-25 t/ha fresh rhizomes',
            seasonality: 'Kharif',
            uses: 'Spice, medicine, cosmetic',
            imageUrl: 'https://example.com/turmeric.jpg',
            language: 'en',
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            category: 'crop',
            commonName: 'Tomato',
            scientificName: 'Solanum lycopersicum',
            family: 'Solanaceae',
            tags: JSON.stringify(['vegetable', 'cash crop', 'annual']),
            growthHabit: 'herb',
            lifecycle: 'annual',
            climate: 'Temperate to tropical, 20-25°C',
            region: 'Karnataka, Andhra Pradesh, Telangana, Maharashtra',
            soil: 'Well-drained sandy loam, pH 6.0-7.0',
            water: '400-800mm, regular irrigation',
            sunlight: 'Full sun, 6-8 hours',
            spacing: '75x45 cm',
            sowingPlanting: 'June-July, October-November, January-February',
            fertilization: 'NPK 80:60:60 kg/ha',
            pests: 'Fruit borer, Whitefly, Aphids',
            diseases: 'Bacterial wilt, Leaf curl, Blight',
            management: 'Hybrid seeds, staking, protected cultivation',
            harvest: '90-120 days, pink/red stage',
            yield: '30-40 t/ha',
            seasonality: 'Kharif, Rabi, Summer',
            uses: 'Vegetable, processing',
            imageUrl: 'https://example.com/tomato.jpg',
            language: 'en',
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            category: 'crop',
            commonName: 'Mustard',
            scientificName: 'Brassica campestris',
            family: 'Brassicaceae',
            tags: JSON.stringify(['rabi', 'oilseed', 'spice']),
            growthHabit: 'herb',
            lifecycle: 'annual',
            climate: 'Cool, 20-25°C, 300-400mm rainfall',
            region: 'Rajasthan, Uttar Pradesh, Madhya Pradesh, Haryana',
            soil: 'Loamy, pH 6.0-7.5',
            water: '300-400mm, 2-3 irrigations',
            sunlight: 'Full sun, 6-8 hours',
            spacing: '45x15 cm',
            sowingPlanting: 'September-October',
            fertilization: 'NPK 80:40:40 kg/ha',
            pests: 'Aphids, Sawfly, Painted bug',
            diseases: 'White rust, Alternaria blight, Downy mildew',
            management: 'Early sowing, seed treatment, resistant varieties',
            harvest: '100-120 days, pods turn brown and seeds hard',
            yield: '2-3 t/ha',
            seasonality: 'Rabi',
            uses: 'Oil, spice, fodder',
            imageUrl: 'https://example.com/mustard.jpg',
            language: 'en',
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            category: 'crop',
            commonName: 'Green Gram',
            scientificName: 'Vigna radiata',
            family: 'Fabaceae',
            tags: JSON.stringify(['kharif', 'pulse', 'nitrogen fixing']),
            growthHabit: 'herb',
            lifecycle: 'annual',
            climate: 'Warm, 25-35°C, 600-750mm rainfall',
            region: 'Andhra Pradesh, Tamil Nadu, Telangana, Odisha',
            soil: 'Sandy loam to clay loam, pH 6.0-7.5',
            water: '400-500mm, 1-2 irrigations',
            sunlight: 'Full sun, 6-8 hours',
            spacing: '30x10 cm',
            sowingPlanting: 'June-August',
            fertilization: 'NPK 20:40:20 kg/ha',
            pests: 'Pod borer, Bean fly, Thrips',
            diseases: 'Leaf spot, Powdery mildew, Root rot',
            management: 'Rhizobium inoculation, seed treatment, IPM',
            harvest: '60-70 days pods turn brown and dry',
            yield: '1-2 t/ha',
            seasonality: 'Kharif',
            uses: 'Pulse, green manure, fodder',
            imageUrl: 'https://example.com/greengram.jpg',
            language: 'en',
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            category: 'crop',
            commonName: 'Groundnut',
            scientificName: 'Arachis hypogaea',
            family: 'Fabaceae',
            tags: JSON.stringify(['kharif', 'oilseed', 'legume']),
            growthHabit: 'herb',
            lifecycle: 'annual',
            climate: 'Hot humid tropical, 27-30°C, 500-750mm rainfall',
            region: 'Gujarat, Andhra Pradesh, Tamil Nadu, Karnataka',
            soil: 'Well-drained sandy loam, pH 6.0-7.0',
            water: '500-750mm, 5-6 irrigations',
            sunlight: 'Full sun, 6-8 hours',
            spacing: '30x10 cm',
            sowingPlanting: 'June-July with monsoon',
            fertilization: 'NPK 20:40:80 kg/ha',
            pests: 'Leaf miner, Spodoptera, Termites',
            diseases: 'Early leaf spot, Rust, Collar rot',
            management: 'Seed treatment foliar sprays',
            harvest: '120-150 days when leaves turn yellow',
            yield: '2-3 t/ha pods',
            seasonality: 'Kharif',
            uses: 'Oil, confectionary, animal feed',
            imageUrl: 'https://example.com/groundnut.jpg',
            language: 'en',
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            category: 'crop',
            commonName: 'Onion',
            scientificName: 'Allium cepa',
            family: 'Amaryllidaceae',
            tags: JSON.stringify(['bulb', 'spice', 'vegetable']),
            growthHabit: 'herb',
            lifecycle: 'biennial',
            climate: 'Cool season, 13-24°C, 750-1000mm rainfall',
            region: 'Maharashtra, Karnataka, Madhya Pradesh, Gujarat',
            soil: 'Well-drained sandy loam, pH 6.0-7.2',
            water: '800-1000mm, regular irrigation',
            sunlight: 'Full sun, 6-8 hours',
            spacing: '15x10 cm',
            sowingPlanting: 'May-June, October-November',
            fertilization: 'NPK 100:50:50 kg/ha',
            pests: 'Thrips, Onion fly, Leaf miner',
            diseases: 'Purple blotch, Downy mildew, Damping-off',
            management: 'Seed treatment, spraying, mulching',
            harvest: '90-120 days when leaves collapse and necks break',
            yield: '15-20 t/ha',
            seasonality: 'Kharif, Rabi',
            uses: 'Vegetable, condiment, medicinal',
            imageUrl: 'https://example.com/onion.jpg',
            language: 'en',
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            category: 'crop',
            commonName: 'Chickpea',
            scientificName: 'Cicer arietinum',
            family: 'Fabaceae',
            tags: JSON.stringify(['rabi', 'pulse', 'protein']),
            growthHabit: 'herb',
            lifecycle: 'annual',
            climate: 'Cool dry, 24-32°C, 400-600mm rainfall',
            region: 'Madhya Pradesh, Rajasthan, Maharashtra, Uttar Pradesh',
            soil: 'Deep black cotton soil, pH 6.0-8.0',
            water: '300-400mm, 1 irrigation',
            sunlight: 'Full sun, 6-8 hours',
            spacing: '30x10 cm',
            sowingPlanting: 'October-November',
            fertilization: 'NPK 20:50:20 kg/ha',
            pests: 'Pod borer, Cutworm, Aphids',
            diseases: 'Wilt, Blight, Botrytis gray mold',
            management: 'Seed treatment, resistant varieties, deep sowing',
            harvest: '100-120 days when pods turn yellow-brown',
            yield: '2-3 t/ha',
            seasonality: 'Rabi',
            uses: 'Pulse, flour, green manure',
            imageUrl: 'https://example.com/chickpea.jpg',
            language: 'en',
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            category: 'tree',
            commonName: 'Mango',
            scientificName: 'Mangifera indica',
            family: 'Anacardiaceae',
            tags: JSON.stringify(['fruit', 'commercial', 'orchard']),
            growthHabit: 'tree',
            lifecycle: 'perennial',
            climate: 'Tropical subtropical, 24-30°C, 750-2500mm rainfall',
            region: 'Uttar Pradesh, Andhra Pradesh, Karnataka, Bihar',
            soil: 'Deep well-drained, pH 5.5-7.5',
            water: '600-1000mm, 25-30 irrigations',
            sunlight: 'Full sun, 8-10 hours',
            spacing: '10x10 m',
            sowingPlanting: 'June-August grafting/planting',
            fertilization: 'NPK 1:0.5:1 kg/tree/year',
            pests: 'Mango hopper, Fruit fly, Mealy bug',
            diseases: 'Powdery mildew, Anthracnose, Stem bleeding',
            management: 'Pruning, IPM, orchard ventilation',
            harvest: '3-8 years start, May-July',
            yield: '40-50 kg/tree mature',
            seasonality: 'Summer',
            uses: 'Fresh fruit, processed products, timber',
            imageUrl: 'https://example.com/mango.jpg',
            language: 'en',
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            category: 'tree',
            commonName: 'Coconut',
            scientificName: 'Cocos nucifera',
            family: 'Arecaceae',
            tags: JSON.stringify(['plantation', 'commercial', 'coastal']),
            growthHabit: 'tree',
            lifecycle: 'perennial',
            climate: 'Humid tropical, 27-32°C, 1000-2500mm rainfall',
            region: 'Kerala, Karnataka, Tamil Nadu, Andhra Pradesh',
            soil: 'Coastal sandy, lateritic, pH 5.5-7.0',
            water: '800-1200mm, 2-3 liter/tree/day',
            sunlight: 'Full sun, 6-8 hours',
            spacing: '7.5x7.5 m triangular',
            sowingPlanting: 'June-December, fresh nuts',
            fertilization: 'NPK 1:0.3:1.2 kg/tree/year',
            pests: 'Rhinoceros beetle, Red palm weevil',
            diseases: 'Lethal yellowing, Bud rot, Stem bleeding',
            management: 'Foliar spraying, field sanitation',
            harvest: '6-8 years start, 12 nuts/bunch',
            yield: '60-70 nuts/tree/year',
            seasonality: 'Year round',
            uses: 'Copra, oil, coir, toddy, timber',
            imageUrl: 'https://example.com/coconut.jpg',
            language: 'en',
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            category: 'tree',
            commonName: 'Neem',
            scientificName: 'Azadirachta indica',
            family: 'Meliaceae',
            tags: JSON.stringify(['medicinal', 'pesticide', 'forestry']),
            growthHabit: 'tree',
            lifecycle: 'perennial',
            climate: 'Hot arid semi-arid, 25-35°C, 400-1200mm rainfall',
            region: 'Rajasthan, Gujarat, Maharashtra, Karnataka',
            soil: 'Black cotton, red soils, pH 6.0-8.0',
            water: 'Drought resistant, minimal',
            sunlight: 'Full sun, 8-10 hours',
            spacing: '5x5 m',
            sowingPlanting: 'June-August',
            fertilization: 'Organic manure',
            pests: 'Scale insects, White ants',
            diseases: 'Canker, Leaf spot, Root rot',
            management: 'Biological control, resistant varieties',
            harvest: '10 years, seed collection',
            yield: '10-50 kg seed/tree/year',
            seasonality: 'Year round',
            uses: 'Medicinal, timber, biopesticide, shade',
            imageUrl: 'https://example.com/neem.jpg',
            language: 'en',
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            category: 'tree',
            commonName: 'Tamarind',
            scientificName: 'Tamarindus indica',
            family: 'Fabaceae',
            tags: JSON.stringify(['fruit', 'medicinal', 'shade']),
            growthHabit: 'tree',
            lifecycle: 'perennial',
            climate: 'Hot semi-arid, 25-35°C, 500-1500mm rainfall',
            region: 'Karnataka, Tamil Nadu, Andhra Pradesh, Maharashtra',
            soil: 'Deep loamy soils, pH 4.5-8.0',
            water: 'Drought resistant',
            sunlight: 'Full sun, 6-8 hours',
            spacing: '10x10 m',
            sowingPlanting: 'May-June',
            fertilization: 'Farmyard manure',
            pests: 'Pod borer, Beetles',
            diseases: 'Powdery mildew, Wilt',
            management: 'Seed treatment, organic spraying',
            harvest: '8-10 years, March-April',
            yield: '100-200 kg pods/tree',
            seasonality: 'Summer',
            uses: 'Food, medicine, timber, shade',
            imageUrl: 'https://example.com/tamarind.jpg',
            language: 'en',
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            category: 'tree',
            commonName: 'Jackfruit',
            scientificName: 'Artocarpus heterophyllus',
            family: 'Moraceae',
            tags: JSON.stringify(['fruit', 'evergreen', 'tropical']),
            growthHabit: 'tree',
            lifecycle: 'perennial',
            climate: 'Humid tropical, 25-40°C, 1000-3000mm rainfall',
            region: 'Kerala, Karnataka, Tamil Nadu, West Bengal',
            soil: 'Rich loamy, pH 6.0-7.5',
            water: '1000-2000mm',
            sunlight: 'Full sun, 6-8 hours',
            spacing: '12x12 m',
            sowingPlanting: 'June-December, seeds or grafts',
            fertilization: 'Organic manure yearly',
            pests: 'Shoot borer, Fruit borer',
            diseases: 'Die-back, Root rot',
            management: 'Pruning, sanitation, mulching',
            harvest: '6-8 years, May-September',
            yield: '20-100 fruits/tree',
            seasonality: 'Summer',
            uses: 'Fresh fruit, chips, timber',
            imageUrl: 'https://example.com/jackfruit.jpg',
            language: 'en',
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            category: 'crop',
            commonName: 'Brinjal',
            scientificName: 'Solanum melongena',
            family: 'Solanaceae',
            tags: JSON.stringify(['vegetable', 'solanaceae', 'year round']),
            growthHabit: 'herb',
            lifecycle: 'annual',
            climate: 'Warm subtropical, 25-35°C',
            region: 'West Bengal, Bihar, Uttar Pradesh, Karnataka',
            soil: 'Well-drained loamy, pH 5.5-6.5',
            water: '600-1200mm, weekly irrigation',
            sunlight: 'Full sun, 8-10 hours',
            spacing: '60x45 cm',
            sowingPlanting: 'Year-round except peak summer',
            fertilization: 'NPK 100:80:60 kg/ha',
            pests: 'Shoot fruit borer, Aphids, Whiteflies',
            diseases: 'Damping-off, Bacterial wilt, Little leaf',
            management: 'Stake support, IPM, resistant varieties',
            harvest: '60-100 days, tender green glossy skin',
            yield: '25-50 t/ha',
            seasonality: 'Year round',
            uses: 'Vegetable, culinary',
            imageUrl: 'https://example.com/brinjal.jpg',
            language: 'en',
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            category: 'crop',
            commonName: 'Cauliflower',
            scientificName: 'Brassica oleracea var. botrytis',
            family: 'Brassicaceae',
            tags: JSON.stringify(['vegetable', 'cole crop', 'cool season']),
            growthHabit: 'herb',
            lifecycle: 'annual',
            climate: 'Cool temperature, 15-25°C',
            region: 'Himachal Pradesh, Karnataka, Uttar Pradesh, Maharashtra',
            soil: 'Well-drained loamy, pH 6.0-7.0',
            water: '600-800mm, frequent irrigation',
            sunlight: 'Full sun, 5-6 hours',
            spacing: '45x45 cm',
            sowingPlanting: 'June-July, October-November',
            fertilization: 'NPK 150:100:100 kg/ha',
            pests: 'Diamondback moth, Aphids, Cutworm',
            diseases: 'Damping-off, Downy mildew, Black rot',
            management: 'Nipping, earthing, pest monitoring',
            harvest: '60-95 days, head tight compact size',
            yield: '20-25 t/ha',
            seasonality: 'Kharif, Rabi',
            uses: 'Vegetable, frozen products',
            imageUrl: 'https://example.com/cauliflower.jpg',
            language: 'en',
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            category: 'crop',
            commonName: 'Carrot',
            scientificName: 'Daucus carota',
            family: 'Apiaceae',
            tags: JSON.stringify(['root vegetable', 'cool season', 'orange']),
            growthHabit: 'herb',
            lifecycle: 'biennial',
            climate: 'Cool, 15-20°C',
            region: 'Himachal Pradesh, Punjab, Haryana, Uttar Pradesh',
            soil: 'Deep loose loamy, pH 6.0-7.0',
            water: '800-1000mm, uniform moisture',
            sunlight: 'Full sun, 6-8 hours',
            spacing: '30x8 cm',
            sowingPlanting: 'August-October, December-January',
            fertilization: 'NPK 100:50:150 kg/ha',
            pests: 'Carrot fly, Aphids, Nematodes',
            diseases: 'Leaf spot, Soft rot',
            management: 'Thinning, mulching, field hygiene',
            harvest: '90-100 days, 1.5-2.5 cm diameter',
            yield: '25-30 t/ha',
            seasonality: 'Winter',
            uses: 'Salad, cooking, juice, frozen',
            imageUrl: 'https://example.com/carrot.jpg',
            language: 'en',
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            category: 'crop',
            commonName: 'Lady Finger',
            scientificName: 'Abelmoschus esculentus',
            family: 'Malvaceae',
            tags: JSON.stringify(['vegetable', 'okra', 'ladyfinger']),
            growthHabit: 'herb',
            lifecycle: 'annual',
            climate: 'Hot humid, 25-35°C, 600-1200mm rainfall',
            region: 'Bihar, Odisha, Andhra Pradesh, Tamil Nadu',
            soil: 'Loamy to shallow loamy, pH 6.0-6.8',
            water: '700-800mm, weekly irrigation',
            sunlight: 'Full sun, 6-8 hours',
            spacing: '45x20 cm',
            sowingPlanting: 'February-July',
            fertilization: 'NPK 100:50:50 kg/ha',
            pests: 'Shoot fruit borer, Leaf roller, Aphids',
            diseases: 'Yellow vein mosaic, Powdery mildew',
            management: 'Seed treatment, summer cultivation, IPM',
            harvest: '50-60 days, 5-10 cm tender pods',
            yield: '10-12 t/ha',
            seasonality: 'Summer, Kharif',
            uses: 'Vegetable, drying, canning',
            imageUrl: 'https://example.com/ladyfinger.jpg',
            language: 'en',
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            category: 'crop',
            commonName: 'Cotton',
            scientificName: 'Gossypium herbaceum',
            family: 'Malvaceae',
            tags: JSON.stringify(['kharif', 'fibre', 'commercial', 'BT']),
            growthHabit: 'herb',
            lifecycle: 'annual',
            climate: 'Tropical subtropical, 27-32°C',
            region: 'Punjab, Haryana, Rajasthan, Gujarat',
            soil: 'Deep black cotton, pH 6.8-8.0',
            water: '700-1200mm, 6-8 irrigations',
            sunlight: 'Full sun, 8-10 hours',
            spacing: '67x30 cm',
            sowingPlanting: 'April-May',
            fertilization: 'NPK 120:60:60 kg/ha',
            pests: 'American bollworm, Pink bollworm, Spodoptera',
            diseases: 'Wilt, Grey mildew, Bacterial blight',
            management: 'BT varieties, IPM, trap crops',
            harvest: '180-210 days, 75% bolls open',
            yield: '3-4 t/ha kapas',
            seasonality: 'Kharif',
            uses: 'Textile, seed oil, fodder',
            imageUrl: 'https://example.com/cotton.jpg',
            language: 'en',
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            category: 'crop',
            commonName: 'Gram',
            scientificName: 'Cicer arietinum',
            family: 'Fabaceae',
            tags: JSON.stringify(['pulse', 'protein', 'rabi']),
            growthHabit: 'herb',
            lifecycle: 'annual',
            climate: 'Cool, 20-30°C',
            region: 'Madhya Pradesh, Rajasthan, Uttar Pradesh, Maharashtra',
            soil: 'Sandy loam to clay loam, pH 6.0-7.0',
            water: '300-400mm, 1-2 irrigations',
            sunlight: 'Full sun, 6-8 hours',
            spacing: '30x10 cm',
            sowingPlanting: 'October-November',
            fertilization: 'NPK 20:50:20 kg/ha',
            pests: 'Pod borer, Cutworm, Aphid',
            diseases: 'Wilt, Blight, Ascochyta blight',
            management: 'Deep sowing, seed treatment, resistant varieties',
            harvest: '120-140 days, pods turn yellow-brown',
            yield: '2-3 t/ha',
            seasonality: 'Rabi',
            uses: 'Pulse, flour, fodder',
            imageUrl: 'https://example.com/gram.jpg',
            language: 'en',
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            category: 'crop',
            commonName: 'Black Gram',
            scientificName: 'Vigna mungo',
            family: 'Fabaceae',
            tags: JSON.stringify(['kharif', 'pulse', 'protein']),
            growthHabit: 'herb',
            lifecycle: 'annual',
            climate: 'Hot, 25-35°C, 650-850mm rainfall',
            region: 'Andhra Pradesh, Tamil Nadu, Uttar Pradesh, Odisha',
            soil: 'Black to red soil, pH 6.0-7.0',
            water: '400-600mm, 1-2 irrigations',
            sunlight: 'Full sun, 6-8 hours',
            spacing: '25x10 cm',
            sowingPlanting: 'June-July',
            fertilization: 'NPK 20:40:20 kg/ha',
            pests: 'Pod borer, Aphid, Whitefly',
            diseases: 'Leaf spot, Powdery mildew, Wilt',
            management: 'Seed treatment, rhizobium, IPM',
            harvest: '70-80 days, pods turn black',
            yield: '1-2 t/ha',
            seasonality: 'Kharif',
            uses: 'Pulse, fodder, green manure',
            imageUrl: 'https://example.com/blackgram.jpg',
            language: 'en',
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            category: 'crop',
            commonName: 'Red Chili',
            scientificName: 'Capsicum annuum',
            family: 'Solanaceae',
            tags: JSON.stringify(['spice', 'chili', 'commercial']),
            growthHabit: 'herb',
            lifecycle: 'annual',
            climate: 'Hot tropical, 25-32°C',
            region: 'Andhra Pradesh, Maharashtra, Telangana, Karnataka',
            soil: 'Light loamy to black, pH 6.0-7.0',
            water: '600-900mm, regular irrigation',
            sunlight: 'Full sun, 8-10 hours',
            spacing: '45x45 cm',
            sowingPlanting: 'October-November',
            fertilization: 'NPK 80:80:60 kg/ha',
            pests: 'Fruit borer, Thrips, Mites',
            diseases: 'Damping-off, Anthracnose, Mosaic',
            management: 'Seed treatment, staking, IPM',
            harvest: '90-150 days, red ripe stage',
            yield: '1-3 t/ha dry',
            seasonality: 'Rabi, Summer',
            uses: 'Spice, medicine, oleoresin',
            imageUrl: 'https://example.com/chili.jpg',
            language: 'en',
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            category: 'crop',
            commonName: 'Sunflower',
            scientificName: 'Helianthus annuus',
            family: 'Asteraceae',
            tags: JSON.stringify(['oilseed', 'kharif', 'commercial']),
            growthHabit: 'herb',
            lifecycle: 'annual',
            climate: 'Semi-arid, 20-28°C',
            region: 'Karnataka, Maharashtra, Telangana, Andhra Pradesh',
            soil: 'Well-drained loamy, pH 6.0-7.5',
            water: '600-800mm, 4-5 irrigations',
            sunlight: 'Full sun, 8-10 hours',
            spacing: '60x30 cm',
            sowingPlanting: 'June-July',
            fertilization: 'NPK 80:50:60 kg/ha',
            pests: 'Head borer, Whitefly, Caterpillars',
            diseases: 'Downy mildew, Rust, Alternaria',
            management: 'Hybrid varieties, crop rotation, IPM',
            harvest: '90-110 days, head yellow and brown',
            yield: '2-4 t/ha seeds',
            seasonality: 'Kharif, Rabi',
            uses: 'Edible oil, bird feed, biodiesel',
            imageUrl: 'https://example.com/sunflower.jpg',
            language: 'en',
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            category: 'crop',
            commonName: 'Sesame',
            scientificName: 'Sesamum indicum',
            family: 'Pedaliaceae',
            tags: JSON.stringify(['oilseed', 'kharif', 'edible oil']),
            growthHabit: 'herb',
            lifecycle: 'annual',
            climate: 'Tropical, 26-34°C, 600-800mm rainfall',
            region: 'Rajasthan, Gujarat, West Bengal, Uttar Pradesh',
            soil: 'Light to medium, pH 6.0-7.5',
            water: '400-500mm, 2-3 irrigations',
            sunlight: 'Full sun, 6-8 hours',
            spacing: '30x15 cm',
            sowingPlanting: 'June-July',
            fertilization: 'NPK 40:20:20 kg/ha',
            pests: 'Shoot fly, Gall fly, Aphids',
            diseases: 'Leaf spot, Bacterial wilt, Powdery mildew',
            management: 'Early sowing, seed treatment, crop rotation',
            harvest: '80-100 days, pods yellow-brown',
            yield: '600-800 kg/ha',
            seasonality: 'Kharif, Summer',
            uses: 'Edible oil, medicine, confectionary',
            imageUrl: 'https://example.com/sesame.jpg',
            language: 'en',
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            category: 'crop',
            commonName: 'Jute',
            scientificName: 'Corchorus capsularis',
            family: 'Tiliaceae',
            tags: JSON.stringify(['fiber', 'commercial', 'monsoon', 'cash crop']),
            growthHabit: 'herb',
            lifecycle: 'annual',
            climate: 'Tropical humid, 24-40°C, 1500-2500mm rainfall',
            region: 'West Bengal, Bihar, Assam, Odisha',
            soil: 'Alluvial river delta, pH 4.8-5.2',
            water: '1500-1700mm, flooded',
            sunlight: 'Full sun, 6-7 hours',
            spacing: '15x8 cm',
            sowingPlanting: 'March-May',
            fertilization: 'NPK 60:30:40 kg/ha',
            pests: 'Stem weevil, Jute hairy caterpillar, Semilooper',
            diseases: 'Stem rot, Alternaria leaf blight',
            management: 'Seed treatment, deep flooding, weeding',
            harvest: '90-150 days, 20% flowering',
            yield: '25-40 q/ha fiber',
            seasonality: 'Kharif',
            uses: 'Sacking, hessian, carpets, paper',
            imageUrl: 'https://example.com/jute.jpg',
            language: 'en',
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            category: 'tree',
            commonName: 'Peepal',
            scientificName: 'Ficus religiosa',
            family: 'Moraceae',
            tags: JSON.stringify(['sacred', 'medicinal', 'avenue']),
            growthHabit: 'tree',
            lifecycle: 'perennial',
            climate: 'Tropical subtropical, 20-45°C',
            region: 'North India, Central India, South India except coast',
            soil: 'Alluvial red lateritic, pH 4.5-7.5',
            water: 'Drought resistant',
            sunlight: 'Full sun, 10-12 hours',
            spacing: '15x15 m',
            sowingPlanting: 'June-September',
            fertilization: 'Farmyard manure',
            pests: 'Scale insects, Aphids',
            diseases: 'Leaf spot, Twig blight',
            management: 'Natural control, sanitation',
            harvest: 'Not applicable, landscaping',
            yield: 'Shade, oxygen, spiritual value',
            seasonality: 'Year round',
            uses: 'Forestry, avenue, religious, medicine',
            imageUrl: 'https://example.com/peepal.jpg',
            language: 'en',
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            category: 'tree',
            commonName: 'Banyan',
            scientificName: 'Ficus benghalensis',
            family: 'Moraceae',
            tags: JSON.stringify(['forestry', 'avenue', 'sacred']),
            growthHabit: 'tree',
            lifecycle: 'perennial',
            climate: 'Tropical subtropical, 20-35°C',
            region: 'Throughout India except very arid',
            soil: 'Most soils, pH 6.0-8.0',
            water: 'Low requirement',
            sunlight: 'Full sun, 8-10 hours',
            spacing: '20x20 m',
            sowingPlanting: 'Monsoon season',
            fertilization: 'Organic manure',
            pests: 'White ants, Caterpillars',
            diseases: 'Leaf spot, Wilt',
            management: 'Natural management',
            harvest: 'Forestry after decades',
            yield: 'Timber, shade, ecosystem service',
            seasonality: 'Year round',
            uses: 'Religious, avenue, fodder, timber',
            imageUrl: 'https://example.com/banyan.jpg',
            language: 'en',
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            category: 'plant',
            commonName: 'Aloe Vera',
            scientificName: 'Aloe vera',
            family: 'Asphodelaceae',
            tags: JSON.stringify(['medicinal', 'ornamental', 'succulent']),
            growthHabit: 'herb',
            lifecycle: 'perennial',
            climate: 'Hot arid, 25-40°C, 200-800mm rainfall',
            region: 'Rajasthan, Gujarat, Andhra Pradesh,
            Maharashtra',
            soil: 'Sandy well-drained, pH 6.0-8.5',
            water: 'Minimal, drought tolerant',
            sunlight: 'Full sun to partial, 6-8 hours',
            spacing: '40x40 cm',
            sowingPlanting: 'Year round, offsets',
            fertilization: 'Compost 20 g/plant',
            pests: 'Mealybugs, Scales, Snails',
            diseases: 'Root rot, Leaf spot',
            management: 'Well-drained medium, control water',
            harvest: '8-24 months, leaves 30 cm',
            yield: '150-200t gel/ha',
            seasonality: 'Year round',
            uses: 'Cosmetic, medicine, juice, ornamental',
            imageUrl: 'https://example.com/aloe.jpg',
            language: 'en',
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            category: 'plant',
            commonName: 'Tulsi',
            scientificName: 'Ocimum tenuiflorum',
            family: 'Lamiaceae',
            tags: JSON.stringify(['medicinal', 'ornamental', 'aromatic']),
            growthHabit: 'herb',
            lifecycle: 'annual',
            climate: 'Tropical subtropical, 15-32°C',
            region: 'Uttar Pradesh, Madhya Pradesh, Maharashtra, Haryana',
            soil: 'Rich loamy, pH 6.0-7.5',
            water: 'Moderate, avoid waterlogging',
            sunlight: 'Full sun, 6-8 hours',
            spacing: '30x20 cm',
            sowingPlanting: 'April-July, seed or cuttings',
            fertilization: 'Vermicompost, 20 g/plant/month',
            pests: 'Aphids, Caterpillars, Thrips',
            diseases: 'Powdery mildew, Root rot',
            management: 'Pinching, organic sprays, sanitation',
            harvest: '60 days, multiple cuttings',
            yield: '10-15t fresh herbs/ha',
            seasonality: 'Year round',
            uses: 'Medicine, tea, essential oil',
            imageUrl: 'https://example.com/tulsi.jpg',
            language: 'en',
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            category: 'crop',
            commonName: 'Garlic',
            scientificName: 'Allium sativum',
            family: 'Amaryllidaceae',
            tags: JSON.stringify(['bulb', 'spice', 'medicinal']),
            growthHabit: 'herb',
            lifecycle: 'annual',
            climate: 'Cool subtropical, 18-30°C',
            region: 'Madhya Pradesh, Uttar Pradesh, Gujarat, Maharashtra',
            soil: 'Well-drained loamy, pH 6.0-7.0',
            water: '600-800mm, regular irrigation',
            sunlight: 'Full sun, 8-10 hours',
            spacing: '15x10 cm',
            sowingPlanting: 'September-November',
            fertilization: 'NPK 150:100:50 kg/ha',
            pests: 'Damping-off fly, Thrips, Mites',
            diseases: 'White rot, Downy mildew, Black mold',
            management: 'Seed treatment, mulching, weed free',
            harvest: '120-150 days, leaves yellowing and lodging',
            yield: '8-10 t/ha',
            seasonality: 'Rabi',
            uses: 'Spice, medicinal, condiment',
            imageUrl: 'https://example.com/garlic.jpg',
            language: 'en',
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            category: 'crop',
            commonName: 'Bitter Gourd',
            scientificName: 'Momordica charantia',
            family: 'Cucurbitaceae',
            tags: JSON.stringify(['vegetable', 'bitter', 'medicinal', 'vine']),
            growthHabit: 'vine',
            lifecycle: 'annual',
            climate: 'Hot humid, 25-32°C',
            region: 'Karnataka, Tamil Nadu, Odisha, Andhra Pradesh',
            soil: 'Well-drained loamy, pH 6.0-7.0',
            water: '600-800mm, avoid waterlogging',
            sunlight: 'Full sun, 8-10 hours',
            spacing: '150x60 cm',
            sowingPlanting: 'January-March, June-July',
            fertilization: 'NPK 100:80:60 kg/ha',
            pests: 'Fruit fly, Epilachna beetle, Aphids',
            diseases: 'Downy mildew, Powdery mildew',
            management: 'Staking, bagging, IPM, spacing',
            harvest: '60-70 days, tender bitter stage',
            yield: '10-15 t/ha',
            seasonality: 'Spring, monsoon, winter',
            uses: 'Vegetable, juice, medicine',
            imageUrl: 'https://example.com/bittergourd.jpg',
            language: 'en',
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            category: 'crop',
            commonName: 'Cabbage',
            scientificName: 'Brassica oleracea var. capitata',
            family: 'Brassicaceae',
            tags: JSON.stringify(['vegetable', 'cole crop', 'cool season']),
            growthHabit: 'herb',
            lifecycle: 'biennial',
            climate: 'Cool, 15-25°C, high humidity',
            region: 'Himachal Pradesh, Uttar Pradesh, Karnataka, Maharashtra',
            soil: 'Well-drained loamy, pH 6.0-7.0',
            water: '700-800mm, frequent irrigation',
            sunlight: 'Full sun, 6-8 hours',
            spacing: '45x30 cm',
            sowingPlanting: 'August-November',
            fertilization: 'NPK 150:100:100 kg/ha',
            pests: 'Diamondback moth, Aphids, Cabbage caterpillar',
            diseases: 'Club root, Black rot, Downy mildew',
            management: 'Staggered sowing, weed control, spraying',
            harvest: '90-110 days, head firm and compact',
            yield: '30-50 t/ha',
            seasonality: 'Winter',
            uses: 'Vegetable, sauerkraut, pickles',
            imageUrl: 'https://example.com/cabbage.jpg',
            language: 'en',
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            category: 'crop',
            commonName: 'Soybean',
            scientificName: 'Glycine max',
            family: 'Fabaceae',
            tags: JSON.stringify(['kharif', 'oilseed', 'protein', 'legume']),
            growthHabit: 'herb',
            lifecycle: 'annual',
            climate: 'Warm humid, 25-35°C, 600-1000mm rainfall',
            region: 'Madhya Pradesh, Maharashtra, Rajasthan, Telangana',
            soil: 'Well-drained, pH 6.0-7.0',
            water: '600-800mm, 2-3 irrigations',
            sunlight: 'Full sun, 6-8 hours',
            spacing: '50x10 cm',
            sowingPlanting: 'June-July with monsoon',
            fertilization: 'NPK 20:60:60 kg/ha',
            pests: 'Girdle beetle, Stem fly, Aphids',
            diseases: 'Rust, Frog eye spot, Powdery mildew',
            management: 'Rhizobium inoculation, weed free, resistant varieties',
            harvest: '95-130 days, pods yellow-brown',
            yield: '2-3 t/ha',
            seasonality: 'Kharif',
            uses: 'Oil, protein, feed, soy products',
            imageUrl: 'https://example.com/soybean.jpg',
            language: 'en',
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            category: 'crop',
            commonName: 'Mint',
            scientificName: 'Mentha piperita',
            family: 'Lamiaceae',
            tags: JSON.stringify(['medicinal', 'aromatic', 'perennial']),
            growthHabit: 'herb',
            lifecycle: 'perennial',
            climate: 'Subtropical, 15-30°C, 800-1500mm rainfall',
            region: 'Uttar Pradesh, Punjab, Haryana, Rajasthan',
            soil: 'Loamy to heavy, pH 6.5-7.5',
            water: '1000-1200mm, weekly irrigation',
            sunlight: 'Full sun, 6-8 hours',
            spacing: '40x40 cm',
            sowingPlanting: 'January-February, July',
            fertilization: 'NPK 100:50:50 kg/ha',
            pests: 'Leaf roller, Cutworm, Aphids',
            diseases: 'Leaf blight, Brown spot, Wilt',
            management: 'Pruning, frequent harvest, IPM',
            harvest: '90-100 days, multiple cuttings yearly',
            yield: '25-30 t fresh herbage/ha',
            seasonality: 'Year round',
            uses: 'Essential oil, culinary, oral care',
            imageUrl: 'https://example.com/mint.jpg',
            language: 'en',
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            category: 'crop',
            commonName: 'Coriander',
            scientificName: 'Coriandrum sativum',
            family: 'Apiaceae',
            tags: JSON.stringify(['spice', 'medicinal', 'leaf']),
            growthHabit: 'herb',
            lifecycle: 'annual',
            climate: 'Cool, 20-25°C, 400-700mm rainfall',
            region: 'Rajasthan, Madhya Pradesh, Uttar Pradesh, Gujarat',
            soil: 'Well-drained sandy loam, pH 6.5-7.5',
            water: '300-400mm, 2-3 irrigations',
            sunlight: 'Full sun to partial, 6-7 hours',
            spacing: '30x20 cm',
            sowingPlanting: 'October-November',
            fertilization: 'NPK 40:60:40 kg/ha',
            pests: 'Aphids, Thrips, Psyllid',
            diseases: 'Powdery mildew, Soft rot',
            management: 'Seed treatment, wider spacing, weeding',
            harvest: '75-90 days, 50% seeds turn yellow',
            yield: '700-1000 kg/ha seeds',
            seasonality: 'Rabi',
            uses: 'Spice, herb, medicine',
            imageUrl: 'https://example.com/coriander.jpg',
            language: 'en',
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            category: 'crop',
            commonName: 'Spinach',
            scientificName: 'Spinacia oleracea',
            family: 'Amaranthaceae',
            tags: JSON.stringify(['leafy', 'green', 'cool season']),
            growthHabit: 'herb',
            lifecycle: 'annual',
            climate: 'Cool, 10-20°C, moisture loving',
            region: 'Punjab, Himachal Pradesh, Uttar Pradesh, Maharashtra',
            soil: 'Well-drained rich, pH 6.0-7.0',
            water: '600-700mm, frequent irrigation',
            sunlight: 'Full sun to partial, 5-6 hours',
            spacing: '15x10 cm',
            sowingPlanting: 'October-November',
            fertilization: 'NPK 40:30:20 kg/ha',
            pests: 'Aphids, Caterpillars, Thrips',
            diseases: 'Downy mildew, Soft rot, Cercospora spot',
            management: 'Successional sowing, proper spacing, spraying',
            harvest: '30-40 days, at 8-10 leaves',
            yield: '10-15 t/ha',
            seasonality: 'Winter, early spring',
            uses: 'Vegetable, salad, soup',
            imageUrl: 'https://example.com/spinach.jpg',
            language: 'en',
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            category: 'crop',
            commonName: 'Pumpkin',
            scientificName: 'Cucurbita moschata',
            family: 'Cucurbitaceae',
            tags: JSON.stringify(['vegetable', 'vine', 'summer']),
            growthHabit: 'vine',
            lifecycle: 'annual',
            climate: 'Hot humid, 25-35°C, 1000-1500mm rainfall',
            region: 'Karnataka, West Bengal, Bihar, Uttar Pradesh',
            soil: 'Well-drained fertile, pH 6.0-7.0',
            water: '600-800mm, weekly irrigation',
            sunlight: 'Full sun, 8-10 hours',
            spacing: '250x100 cm',
            sowingPlanting: 'June-July',
            fertilization: 'NPK 120:60:60 kg/ha',
            pests: 'Fruit fly, Aphids, Whitefly',
            diseases: 'Downy mildew, Anthracnose, Wilt',
            management: 'Pitting, staking, bagging, IPM',
            harvest: '90-120 days, yellow rind stage',
            yield: '20-30 t/ha',
            seasonality: 'Kharif',
            uses: 'Vegetable, pies, cattle feed',
            imageUrl: 'https://example.com/pumpkin.jpg',
            language: 'en',
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            category: 'tree',
            commonName: 'Cashew',
            scientificName: 'Anacardium occidentale',
            family: 'Anacardiaceae',
            tags: JSON.stringify(['nut', 'commercial', 'orchard', 'tree']),
            growthHabit: 'tree',
            lifecycle: 'perennial',
            climate: 'Warm tropical, 20-35°C, 1000-2000mm rainfall',
            region: 'Goa, Karnataka, Kerala, Maharashtra, Odisha',
            soil: 'Red lateritic, coastal sandy, pH 5.0-8.0',
            water: '1000-1500mm, 4-5 irrigations',
            sunlight: 'Full sun, 8-10 hours',
            spacing: '7x7 m',
            sowingPlanting: 'June-September',
            fertilization: 'NPK 1:0.2:1 kg/tree',
            pests: 'Tea mosquito bug, Stem borer, Caterpillar',
            diseases: 'Anthracnose, Twig dieback, Pink disease',
            management: 'Pruning, IPM, spray schedules',
            harvest: '3-4 years, January-May',
            yield: '7-10 kg nuts/tree',
            seasonality: 'Winter',
            uses: 'Nut, kernel, apple, timber',
            imageUrl: 'https://example.com/cashew.jpg',
            language: 'en',
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            category: 'crop',
            commonName: 'Methi',
            scientificName: 'Trigonella foenum-graecum',
            family: 'Fabaceae',
            tags: JSON.stringify(['leaf', 'spice', 'medicinal', 'annual']),
            growthHabit: 'herb',
            lifecycle: 'annual',
            climate: 'Cool dry, 10-27°C, 600-800mm rainfall',
            region: 'Rajasthan, Gujarat, Uttar Pradesh, Punjab',
            soil: 'Sandy loam to clay loam, pH 6.0-7.0',
            water: '400-500mm, 2-3 irrigations',
            sunlight: 'Full sun, 6-8 hours',
            spacing: '25x10 cm',
            sowingPlanting: 'October-November',
            fertilization: 'NPK 20:30:20 kg/ha',
            pests: 'Aphids, Leaf miners, Caterpillars',
            diseases: 'Root rot, Powdery mildew, Wilt',
            management: 'Seed treatment, wide spacing, crop rotation',
            harvest: '90-110 days, pods yellow-brown',
            yield: '800-1000 kg/ha seeds',
            seasonality: 'Rabi',
            uses: 'Spice, vegetable, medicine, fodder',
            imageUrl: 'https://example.com/methi.jpg',
            language: 'en',
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            category: 'crop',
            commonName: 'Cumin',
            scientificName: 'Cuminum cyminum',
            family: 'Apiaceae',
            tags: JSON.stringify(['spice', 'medicinal', 'arid', 'rabi']),
            growthHabit: 'herb',
            lifecycle: 'annual',
            climate: 'Semi-arid, 15-25°C, 300-400mm rainfall',
            region: 'Rajasthan, Gujarat, Uttar Pradesh',
            soil: 'Sandy loam, pH 6.5-8.5',
            water: '300-350mm, 2 irrigations',
            sunlight: 'Full sun, 6-8 hours',
            spacing: '20x10 cm',
            sowingPlanting: 'November-December',
            fertilization: 'NPK 20:50:20 kg/ha',
            pests: 'Aphids, Thrips, Cutworm',
            diseases: 'Powdery mildew, Wilt, Blight',
            management: 'Seed treatment, weeding, timely harvest',
            harvest: '110-130 days, seeds light brown',
            yield: '600-800 kg/ha',
            seasonality: 'Rabi',
            uses: 'Spice, medicine, oil',
            imageUrl: 'https://example.com/cumin.jpg',
            language: 'en',
            createdAt: Date.now(),
            updatedAt: Date.now(),
        }
    ];

    await db.insert(species).values(sampleSpecies);
    
    console.log('✅ Species seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});